# This is a basic workflow to help you get started with boman.ai

name: Bomanai Scanner
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Boman-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      #- name: docker
      #  run: pip install --extra-index-url https://test.pypi.org/simple/ docker
      - name: Install packages
        run: sudo pip install boman-cli
        #sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat
        #sudo pip install boman-cli
      - name: Run scan  
        run: sudo boman-cli -a run -at 53244497-2c6d-4f22-b549-d8cefa6032c0 -ct ad752d56-f8e8-4b3c-a70a-d35abaee21b3
        #-at b4eb5daf-60f5-4933-8476-9919bfa2508f -ct b1de9563-38b8-40d1-80d9-62b88af4749b
        #sudo boman-cli-uat -a run -u https://qa.boman.ai 
        #-at b4eb5daf-60f5-4933-8476-9919bfa2508f -ct b1de9563-38b8-40d1-80d9-62b88af4749b
        #sudo boman-cli -a run -u https://dashboard.boman.ai/

        #run: sudo boman-cli -a run
        #run: sudo boman-cli -a run -zap_session_script Juice_Shop_Session_Management.js
